-- PROCEDURE CRIADA PARA INSERÇÃO DE UM NOVO CONTATO --
--													 --
--													 --
--													 --
-------------------------------------------------------
CREATE PROCEDURE INCLUIR_CONTATO(@NOME VARCHAR(80),
								@ENDERECO VARCHAR(240),
								@TELEFONE VARCHAR(15),
								@DATA_NASC datetime,
								@ID_CATEGORIA INT)
AS
BEGIN

DECLARE @ID_CONTATO INT;

INSERT INTO CONTATO(NOME,ENDERECO,TELEFONE,DATA_NASC)
VALUES (@NOME,@ENDERECO,@TELEFONE,@DATA_NASC);

SELECT @ID_CONTATO = CAST(SCOPE_IDENTITY() AS INT);

INSERT INTO RELAC_CAT_CONT(ID_CATEGORIA,ID_CONTATO)
VALUES(@ID_CATEGORIA,@ID_CONTATO);

SELECT @ID_CONTATO;
END;