-- PROCEDURE CRIADA PARA ATUALIZAÇÃO DE UM CONTATO --
--													 --
--													 --
--													 --
-------------------------------------------------------
CREATE PROCEDURE ALTER_CONTATO(@ID_CONTATO INT,
								@NOME VARCHAR(80),
								@ENDERECO VARCHAR(240),
								@TELEFONE VARCHAR(15),
								@DATA_NASC datetime,
								@ID_CATEGORIA INT,
								@ID_CATEGORIA_ORIG INT)
AS
BEGIN

UPDATE CONTATO
SET NOME = @NOME,
	ENDERECO = @ENDERECO,
	TELEFONE = @TELEFONE,
	DATA_NASC = @DATA_NASC
WHERE ID =  @ID_CONTATO;

UPDATE RELAC_CAT_CONT
SET ID_CATEGORIA = @ID_CATEGORIA
WHERE ID_CONTATO =  @ID_CONTATO
AND ID_CATEGORIA = @ID_CATEGORIA_ORIG;


END;