-- PROCEDURE CRIADA PARA INSERÇÃO DE UMA NOVA CATEGORIA --
--													 --
--													 --
--													 --
-------------------------------------------------------
CREATE PROCEDURE INCLUIR_CATEGORIA(@DESCRICAO VARCHAR(80))
AS
BEGIN

DECLARE @ID_CATEGORIA INT;

INSERT INTO CATEGORIA(CATEGORIA) VALUES (@DESCRICAO);

SELECT @ID_CATEGORIA = CAST(SCOPE_IDENTITY() AS INT);

END;